<?php

namespace Website\WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
	/*
	 * Methode pour recuperer toutes les categories
	*/
	public  function getAllCategories(){
		$qb=$this->createQueryBuilder('c')
		->select('c')
		->getQuery()
		->getResult();
		return $qb;
	}
}
