<?php

namespace Website\WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompetencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetencesRepository extends EntityRepository
{
	public function getAllCompetences(){
		$qb=$this->createQueryBuilder('c')
				 ->select('c')
				 ->getQuery()
				 ->getResult();
		return $qb;
	}
}
