<?php

namespace Website\WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SlideshowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideshowRepository extends EntityRepository
{
	/*
	 * Methode pour recuperer toutes les slides
	*/
	public  function getAllSlideshows(){
		$qb=$this->createQueryBuilder('s')
		->select('s')
		->getQuery()
		->getResult();
		return $qb;
	}
}
