Categorie:
    type: entity
    table: categorie
    id:
        idcategorie:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idCategorie
            generator:
                strategy: IDENTITY
    fields:
        libelle:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
